### ISSUE TITLE
Problem: no automation of release builds

### ISSUE THREAD

**Issue by leejw51crypto** [crypto-com/chain#1028]
add automatic release builder
1. check git master branch
2. build linux-binary automatically
3. include all binarines , so that user can simply run with just one command
all processes done automatically

**Comment by yihuang** [comment]
Something like this:

`.drone.yml`:
```
---
kind: pipeline
name: publish

steps:
- name: docker
  image: plugins/docker
  settings:
    repo: crypto-chain
    dockerfile: docker/Dockerfile.new
    auto_tag: true
    username:
      from_secret: DOCKER_USERNAME
    auth:
      from_secret: DOCKER_AUTH_TOKEN
```
